// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

type CollectedID struct {
	ProjectKey string `json:"project_key"`
	RemoteID   string `json:"remote_id"`
	CreatedAt  int64  `json:"created_at"`
}
