// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package database

import (
	"context"
)

const insertCollectedID = `-- name: InsertCollectedID :execrows
INSERT INTO collected_ids (project_key, remote_id, created_at)
VALUES (?1, ?2, ?3)
ON CONFLICT (project_key, remote_id) DO NOTHING
`

type InsertCollectedIDParams struct {
	ProjectKey string `json:"project_key"`
	RemoteID   string `json:"remote_id"`
	CreatedAt  int64  `json:"created_at"`
}

func (q *Queries) InsertCollectedID(ctx context.Context, arg InsertCollectedIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertCollectedID, arg.ProjectKey, arg.RemoteID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listCollectedIDs = `-- name: ListCollectedIDs :many
SELECT remote_id, created_at
FROM collected_ids
WHERE project_key = ?1
  AND created_at >= ?2
  AND created_at < ?3
ORDER BY created_at DESC, remote_id DESC
LIMIT ?4
`

type ListCollectedIDsParams struct {
	ProjectKey string `json:"project_key"`
	Since      int64  `json:"since"`
	Until      int64  `json:"until"`
	PageSize   int64  `json:"page_size"`
}

type ListCollectedIDsRow struct {
	RemoteID  string `json:"remote_id"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) ListCollectedIDs(ctx context.Context, arg ListCollectedIDsParams) ([]ListCollectedIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCollectedIDs,
		arg.ProjectKey,
		arg.Since,
		arg.Until,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollectedIDsRow
	for rows.Next() {
		var i ListCollectedIDsRow
		if err := rows.Scan(&i.RemoteID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectedIDsAfter = `-- name: ListCollectedIDsAfter :many
SELECT remote_id, created_at
FROM collected_ids
WHERE project_key = ?1
  AND created_at >= ?2
  AND created_at < ?3
  AND (
    created_at < ?4
    OR (created_at = ?4 AND remote_id < ?5)
  )
ORDER BY created_at DESC, remote_id DESC
LIMIT ?6
`

type ListCollectedIDsAfterParams struct {
	ProjectKey      string `json:"project_key"`
	Since           int64  `json:"since"`
	Until           int64  `json:"until"`
	CursorCreatedAt int64  `json:"cursor_created_at"`
	CursorRemoteID  string `json:"cursor_remote_id"`
	PageSize        int64  `json:"page_size"`
}

type ListCollectedIDsAfterRow struct {
	RemoteID  string `json:"remote_id"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) ListCollectedIDsAfter(ctx context.Context, arg ListCollectedIDsAfterParams) ([]ListCollectedIDsAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listCollectedIDsAfter,
		arg.ProjectKey,
		arg.Since,
		arg.Until,
		arg.CursorCreatedAt,
		arg.CursorRemoteID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollectedIDsAfterRow
	for rows.Next() {
		var i ListCollectedIDsAfterRow
		if err := rows.Scan(&i.RemoteID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
